INSERT INTO rest_db_access("id", "name") VALUES (1, 'Penny')
INSERT INTO rest_db_access("id", "name") VALUES (2, 'Sheldon')
INSERT INTO rest_db_access("id", "name") VALUES (3, 'Amy')
INSERT INTO rest_db_access("id", "name") VALUES (4, 'Leonard')
INSERT INTO rest_db_access("id", "name") VALUES (5, 'Bernadette')
INSERT INTO rest_db_access("id", "name") VALUES (6, 'Raj')
INSERT INTO rest_db_access("id", "name") VALUES (7, 'Howard')
INSERT INTO rest_db_access("id", "name") VALUES (8, 'Priya')